return
{
-- Friends
SteamAPI_ISteamFriends_SetPersonaName="SetPersonaNameResponse_t",
SteamAPI_ISteamFriends_DownloadClanActivityCounts="DownloadClanActivityCountsResult_t",
SteamAPI_ISteamFriends_RequestClanOfficerList="ClanOfficerListResponse_t",
SteamAPI_ISteamFriends_JoinClanChatRoom="JoinClanChatRoomCompletionResult_t",
SteamAPI_ISteamFriends_GetFollowerCount="FriendsGetFollowerCount_t",
SteamAPI_ISteamFriends_IsFollowing="FriendsIsFollowing_t",
SteamAPI_ISteamFriends_EnumerateFollowingList="FriendsEnumerateFollowingList_t",

-- Matchmaking
SteamAPI_ISteamMatchmaking_RequestLobbyList="LobbyMatchList_t",
SteamAPI_ISteamMatchmaking_CreateLobby="LobbyCreated_t",
SteamAPI_ISteamMatchmaking_JoinLobby="LobbyEnter_t",

-- Remote Storage
SteamAPI_ISteamRemoteStorage_FileWriteAsync="RemoteStorageFileWriteAsyncComplete_t",
SteamAPI_ISteamRemoteStorage_FileReadAsync="RemoteStorageFileReadAsyncComplete_t",
SteamAPI_ISteamRemoteStorage_FileShare="RemoteStorageFileShareResult_t",
SteamAPI_ISteamRemoteStorage_UGCDownload="RemoteStorageDownloadUGCResult_t",
SteamAPI_ISteamRemoteStorage_PublishWorkshopFile="RemoteStoragePublishFileProgress_t",
SteamAPI_ISteamRemoteStorage_CommitPublishedFileUpdate="RemoteStorageUpdatePublishedFileResult_t",
SteamAPI_ISteamRemoteStorage_GetPublishedFileDetails="RemoteStorageGetPublishedFileDetailsResult_t",
SteamAPI_ISteamRemoteStorage_DeletePublishedFile="RemoteStorageDeletePublishedFileResult_t",
SteamAPI_ISteamRemoteStorage_EnumerateUserPublishedFiles="RemoteStorageEnumerateUserPublishedFilesResult_t",
SteamAPI_ISteamRemoteStorage_SubscribePublishedFile="RemoteStorageSubscribePublishedFileResult_t",
SteamAPI_ISteamRemoteStorage_EnumerateUserSubscribedFiles="RemoteStorageEnumerateUserSubscribedFilesResult_t",
SteamAPI_ISteamRemoteStorage_UnsubscribePublishedFile="RemoteStorageUnsubscribePublishedFileResult_t",
SteamAPI_ISteamRemoteStorage_GetPublishedItemVoteDetails="RemoteStorageGetPublishedItemVoteDetailsResult_t",
SteamAPI_ISteamRemoteStorage_UpdateUserPublishedItemVote="RemoteStorageUpdateUserPublishedItemVoteResult_t",
SteamAPI_ISteamRemoteStorage_GetUserPublishedItemVoteDetails="RemoteStorageGetPublishedItemVoteDetailsResult_t",
SteamAPI_ISteamRemoteStorage_EnumerateUserSharedWorkshopFiles="RemoteStorageEnumerateUserSharedWorkshopFilesResult_t",
SteamAPI_ISteamRemoteStorage_PublishVideo="RemoteStoragePublishFileProgress_t",
SteamAPI_ISteamRemoteStorage_SetUserPublishedFileAction="RemoteStorageSetUserPublishedFileActionResult_t",
SteamAPI_ISteamRemoteStorage_EnumeratePublishedFilesByUserAction="RemoteStorageEnumeratePublishedFilesByUserActionResult_t",
SteamAPI_ISteamRemoteStorage_EnumeratePublishedWorkshopFiles="RemoteStorageEnumerateWorkshopFilesResult_t",
SteamAPI_ISteamRemoteStorage_UGCDownloadToLocation="RemoteStorageDownloadUGCResult_t",

-- User Generated Content 
SteamAPI_ISteamUGC_SendQueryUGCRequest="SteamUGCQueryCompleted_t",
SteamAPI_ISteamUGC_RequestUGCDetails="SteamUGCRequestUGCDetailsResult_t",
SteamAPI_ISteamUGC_CreateItem="CreateItemResult_t",
SteamAPI_ISteamUGC_SubmitItemUpdate="SubmitItemUpdateResult_t",
SteamAPI_ISteamUGC_SetUserItemVote="SetUserItemVoteResult_t",
SteamAPI_ISteamUGC_GetUserItemVote="GetUserItemVoteResult_t",
SteamAPI_ISteamUGC_AddItemToFavorites="UserFavoriteItemsListChanged_t",
SteamAPI_ISteamUGC_RemoveItemFromFavorites="UserFavoriteItemsListChanged_t",
SteamAPI_ISteamUGC_SubscribeItem="RemoteStorageSubscribePublishedFileResult_t",
SteamAPI_ISteamUGC_UnsubscribeItem="RemoteStorageUnsubscribePublishedFileResult_t",
SteamAPI_ISteamUGC_StartPlaytimeTracking="StartPlaytimeTrackingResult_t",
SteamAPI_ISteamUGC_StopPlaytimeTracking="StopPlaytimeTrackingResult_t",
SteamAPI_ISteamUGC_StopPlaytimeTrackingForAllItems="StopPlaytimeTrackingResult_t",
SteamAPI_ISteamUGC_AddDependency="AddUGCDependencyResult_t",
SteamAPI_ISteamUGC_RemoveDependency="RemoveUGCDependencyResult_t",
SteamAPI_ISteamUGC_AddAppDependency="AddAppDependencyResult_t",
SteamAPI_ISteamUGC_RemoveAppDependency="RemoveAppDependencyResult_t",
SteamAPI_ISteamUGC_GetAppDependencies="GetAppDependenciesResult_t",
SteamAPI_ISteamUGC_DeleteItem="DeleteItemResult_t",
SteamAPI_ISteamUGC_DownloadItem="DownloadItemResult_t",

-- User
SteamAPI_ISteamUser_RequestEncryptedAppTicket="EncryptedAppTicketResponse_t",
SteamAPI_ISteamUser_RequestStoreAuthURL="StoreAuthURLResponse_t",
--SteamAPI_ISteamUser_GetMarketEligibility="",

-- User Stats
SteamAPI_ISteamUserStats_RequestUserStats="UserStatsReceived_t",
SteamAPI_ISteamUserStats_FindOrCreateLeaderboard="LeaderboardFindResult_t",
SteamAPI_ISteamUserStats_FindLeaderboard="LeaderboardFindResult_t",
SteamAPI_ISteamUserStats_DownloadLeaderboardEntries="LeaderboardScoresDownloaded_t",
SteamAPI_ISteamUserStats_DownloadLeaderboardEntriesForUsers="LeaderboardScoresDownloaded_t",
SteamAPI_ISteamUserStats_UploadLeaderboardScore="LeaderboardScoreUploaded_t",
SteamAPI_ISteamUserStats_AttachLeaderboardUGC="LeaderboardUGCSet_t",
--SteamAPI_ISteamUserStats_GetNumberOfCurrentPlayers="",
SteamAPI_ISteamUserStats_RequestGlobalAchievementPercentages="GlobalAchievementPercentagesReady_t",

-- Utilis 
SteamAPI_ISteamUtils_CheckFileSignature="CheckFileSignature_t",
}