return
{
  arabic = "ar",
  bulgarian = "bg",
  schinese = "zh_cn",
  tchinese = "zh_tw",
  czech = "cs",
  danish = "da",
  dutch = "nl",
  english = "en",
  finnish = "fi",
  french = "fr",
  german = "de",
  greek = "el",
  hungarian = "hu",
  italian = "it",
  japanese = "ja",
  koreana = "ko",
  norwegian = "no",
  polish = "pl",
  portuguese = "pt",
  brazilian = "pt_br",
  romanian = "ro",
  russian = "ru",
  spanish = "es",
  latam = "es_419",
  swedish = "sv",
  thai = "th",
  turkish = "tr",
  ukrainian = "uk",
  vietnamese = "vn",
}