name: AppImage Creation

on:
  push:
    branches:
      - Rewrite
  pull_request:
    branches:
      - Rewrite

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3
    - name: create linux app image
      run: |
        make appimage