name: Rit - Lovefile

on:
  push:
    branches: [ beta ]
  pull_request:
    branches: [ beta ]

  workflow_dispatch:

jobs:
  lovefile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          make lovefile

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: rit
          path: build/lovefile
